spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://buildtestdb.c3koiucce2jf.ap-northeast-2.rds.amazonaws.com:3306/buildtestdb
    username: admin
    password: ajeong2311#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect